# Generated by Django 5.2.2 on 2025-08-01 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JK', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_movie',
            name='Photo',
            field=models.CharField(default="{% static 'kesari.jpg' %}", max_length=100),
        ),
    ]
