# Generated by Django 5.2.2 on 2025-08-08 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JK', '0002_add_movie_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='coming_movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('C_Name', models.CharField(max_length=20)),
                ('C_Genre', models.CharField(max_length=20)),
                ('C_Realese_Date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TicketBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=255)),
                ('release_date', models.DateField()),
                ('theater_name', models.CharField(max_length=255)),
                ('theater_address', models.TextField()),
                ('show_time', models.TimeField()),
                ('seat_numbers', models.CharField(max_length=255)),
                ('seat_type', models.CharField(max_length=50)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('booking_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
