# Generated by Django 5.2.2 on 2025-08-23 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JK', '0003_coming_movie_ticketbooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_movie',
            name='Photo',
            field=models.ImageField(upload_to='movies/'),
        ),
    ]
