# Generated by Django 5.2.2 on 2025-08-23 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JK', '0004_alter_add_movie_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='coming_movie',
            name='C_Photo',
            field=models.ImageField(blank=True, null=True, upload_to='movies/'),
        ),
        migrations.AlterField(
            model_name='add_movie',
            name='Genre',
            field=models.CharField(max_length=30),
        ),
    ]
