# Generated by Django 5.2.2 on 2025-08-27 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JK', '0005_coming_movie_c_photo_alter_add_movie_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password1', models.CharField(max_length=128)),
                ('password2', models.CharField(max_length=128)),
            ],
        ),
    ]
