# Generated by Django 5.2.2 on 2025-09-20 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JK', '0006_registeruser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theatre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('T_Name', models.CharField(max_length=150)),
                ('T_Address', models.TextField()),
                ('T_Screen', models.CharField(max_length=150)),
                ('T_Facility', models.CharField(max_length=150)),
                ('S_Time', models.JSONField(default=list)),
            ],
        ),
    ]
