# Generated by Django 5.2.2 on 2025-09-20 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JK', '0007_theatre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieName', models.CharField(max_length=200)),
                ('releaseDate', models.DateField()),
                ('theaterName', models.CharField(max_length=200)),
                ('theaterAddress', models.TextField()),
                ('showTime', models.CharField(max_length=50)),
                ('seatNumbers', models.JSONField(default=list)),
                ('seatType', models.CharField(max_length=50)),
                ('totalPrice', models.IntegerField()),
                ('bookingTime', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JK.registeruser')),
            ],
        ),
        migrations.DeleteModel(
            name='Theatre',
        ),
        migrations.DeleteModel(
            name='TicketBooking',
        ),
    ]
