# Generated by Django 5.2.2 on 2025-09-25 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JK', '0008_booking_delete_theatre_delete_ticketbooking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
