# Generated by Django 5.2.2 on 2025-10-17 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JK', '0009_delete_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theatre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('screen', models.CharField(max_length=50)),
                ('facilities', models.TextField()),
                ('times', models.JSONField(default=list)),
            ],
        ),
    ]
