# Generated by Django 5.2.2 on 2025-10-17 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JK', '0010_theatre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theatre',
            name='times',
        ),
        migrations.AddField(
            model_name='theatre',
            name='show_times',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='theatre',
            name='facilities',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='theatre',
            name='screen',
            field=models.CharField(max_length=100),
        ),
    ]
