# Generated by Django 5.2.2 on 2025-10-28 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JK', '0011_remove_theatre_times_theatre_show_times_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_numbers', models.JSONField()),
                ('seat_type', models.CharField(max_length=50)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('show_time', models.CharField(max_length=50)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JK.add_movie')),
                ('theatre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JK.theatre')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JK.registeruser')),
            ],
        ),
    ]
