# Generated by Django 5.2.2 on 2025-11-13 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JK', '0012_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeruser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='users/'),
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
