# Generated by Django 5.2.2 on 2025-11-13 16:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JK', '0013_registeruser_photo_delete_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tickets', models.PositiveIntegerField()),
                ('booked_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JK.add_movie')),
                ('theatre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JK.theatre')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JK.registeruser')),
            ],
        ),
    ]
