# Generated by Django 5.2.2 on 2025-11-15 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JK', '0015_booking_seat_numbers_booking_seat_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registeruser',
            name='username',
        ),
        migrations.AddField(
            model_name='registeruser',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registeruser',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='registeruser',
            name='gender',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='registeruser',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='registeruser',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
