# Generated by Django 5.2.2 on 2025-11-15 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JK', '0016_remove_registeruser_username_registeruser_birth_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registeruser',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='registeruser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='registeruser',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='registeruser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='registeruser',
            name='phone',
        ),
        migrations.AddField(
            model_name='registeruser',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
