# Generated by Django 5.2.2 on 2025-11-22 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JK', '0018_registeruser_birth_date_registeruser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_movie',
            name='Certificate',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='add_movie',
            name='Description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='add_movie',
            name='Duration',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='add_movie',
            name='Hero',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='add_movie',
            name='Heroine',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='add_movie',
            name='Language',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='add_movie',
            name='Rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='add_movie',
            name='Status',
            field=models.CharField(blank=True, choices=[('Now Showing', 'Now Showing'), ('Coming Soon', 'Coming Soon')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='add_movie',
            name='Trailer_Link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='add_movie',
            name='Genre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='add_movie',
            name='Movie_Name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='add_movie',
            name='Photo',
            field=models.ImageField(upload_to='movies'),
        ),
    ]
