# Generated by Django 5.2.2 on 2025-11-22 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JK', '0019_add_movie_certificate_add_movie_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_movie',
            name='Status',
        ),
    ]
