# Generated by Django 5.2.2 on 2025-11-22 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JK', '0020_remove_add_movie_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='coming_movie',
            name='C_Certificate',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='coming_movie',
            name='C_Description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coming_movie',
            name='C_Duration',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='coming_movie',
            name='C_Hero',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='coming_movie',
            name='C_Heroine',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='coming_movie',
            name='C_Language',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='coming_movie',
            name='C_Rating',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='coming_movie',
            name='C_Trailer_Link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coming_movie',
            name='C_Genre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='coming_movie',
            name='C_Name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='coming_movie',
            name='C_Photo',
            field=models.ImageField(blank=True, null=True, upload_to='movies'),
        ),
        migrations.AlterField(
            model_name='coming_movie',
            name='C_Realese_Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
