# Generated by Django 5.2.2 on 2025-11-22 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JK', '0021_coming_movie_c_certificate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_movie',
            name='id',
        ),
        migrations.RemoveField(
            model_name='coming_movie',
            name='id',
        ),
        migrations.RemoveField(
            model_name='registeruser',
            name='id',
        ),
        migrations.RemoveField(
            model_name='theatre',
            name='id',
        ),
        migrations.AddField(
            model_name='add_movie',
            name='a_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='coming_movie',
            name='c_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='registeruser',
            name='u_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='theatre',
            name='t_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
