# Generated by Django 5.2.2 on 2025-11-22 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JK', '0023_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='id',
        ),
        migrations.AddField(
            model_name='booking',
            name='b_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
