# Generated by Django 5.2.2 on 2025-11-25 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JK', '0024_remove_booking_id_booking_b_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeruser',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
