# Generated by Django 5.2.2 on 2025-11-26 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JK', '0025_alter_registeruser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='show_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
