# Generated by Django 5.2.2 on 2025-11-26 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JK', '0026_booking_show_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancelBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_date', models.DateField(blank=True, null=True)),
                ('show_time', models.CharField(max_length=50)),
                ('seats', models.CharField(max_length=200)),
                ('seat_type', models.CharField(default='Regular', max_length=50)),
                ('tickets', models.PositiveIntegerField(default=1)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cancelled_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JK.add_movie')),
                ('theatre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JK.theatre')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JK.registeruser')),
            ],
        ),
    ]
