# Generated by Django 5.2.2 on 2025-11-26 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JK', '0027_cancelbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
