# Generated by Django 5.2.2 on 2025-11-26 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JK', '0028_booking_is_cancelled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='is_cancelled',
        ),
        migrations.AddField(
            model_name='booking',
            name='seat_numbers',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='SeatLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_date', models.DateField()),
                ('show_time', models.CharField(max_length=20)),
                ('seat_number', models.CharField(max_length=10)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JK.add_movie')),
                ('theatre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JK.theatre')),
            ],
        ),
    ]
